import os,sys,math

y=10
masses = [200+x*y for x in range(0,281)] #200-3000
masses.append(3500)
masses.append(4000)
#print masses

f=open('lqNLOxsec_single_bQuark_lambda_1.txt','w')
f.write('##################################'+'\n')
f.write('#                                '+'\n')
f.write('#  File to run NLO LQ production '+'\n')
f.write('#  cross section calculations in '+'\n')
f.write('#  MadGraph using the LQ toolbox '+'\n')
f.write('#  https://lqnlo.hepforge.org    '+'\n')
f.write('#                                '+'\n')
f.write('#  width = m_LQ/(16pi)           '+'\n')
f.write('#  mu_r=mu_f=m_LQ                '+'\n')
f.write('#  lamdba_lq=1.0                 '+'\n')
f.write('#                                '+'\n')
f.write('#  Ariana Gonzalez 12/2022           '+'\n')
f.write('##################################'+'\n')
f.write('import model Leptokvark/Leptokvark_NLO'+'\n')
f.write('generate p p > lq ta- $$ lq~ [QCD]'+'\n')
f.write('add process p p > lq~ ta+ $$ lq [QCD]'+'\n')
f.write('output LQLQ_Leptokvark_singleB'+'\n')
f.write('y'+'\n')
for mass in masses:
    m = float(mass)
    f.write('launch LQLQ_Leptokvark_singleB'+'\n')
    f.write('fixed_order = ON'+'\n')
    f.write('0'+'\n')
    f.write('set pdlabel lhapdf'+'\n')
    f.write('set lhaid 90500'+'\n')
    f.write('set nevents 1'+'\n')
    f.write('set mass 9000002 '+str(m)+'\n')
    f.write('set width 9000002 '+str(m/16/math.pi)+'\n')
    f.write('set fixed_ren_scale True'+'\n')
    f.write('set fixed_fac_scale True'+'\n')
    f.write('set mur_ref_fixed '+str(m)+'\n')
    f.write('set muf_ref_fixed '+str(m)+'\n')
    f.write('set reweight_pdf True'+'\n')
    f.write('set req_acc_fo 0.01'+'\n')
    f.write('set gul 1.0'+'\n') #doesn't matter that other terms are on, model only has u+ve, d+e, c+vmu, s+mu, b+ta 
    f.write('set gcl 1.0'+'\n')
    f.write('set gdl 1.0'+'\n')
    f.write('set gsl 1.0'+'\n')
    f.write('set gbl 1.0'+'\n')
f.close()


f=open('lqNLOxsec_single_bQuark_lambda_0p1.txt','w')
f.write('##################################'+'\n')
f.write('#                                '+'\n')
f.write('#  File to run NLO LQ production '+'\n')
f.write('#  cross section calculations in '+'\n')
f.write('#  MadGraph using the LQ toolbox '+'\n')
f.write('#  https://lqnlo.hepforge.org    '+'\n')
f.write('#                                '+'\n')
f.write('#  width = m_LQ/(16pi)           '+'\n')
f.write('#  mu_r=mu_f=m_LQ                '+'\n')
f.write('#  lamdba_lq=1.0                 '+'\n')
f.write('#                                '+'\n')
f.write('#  Ariana Gonzalez 12/2022           '+'\n')
f.write('##################################'+'\n')
f.write('import model Leptokvark/Leptokvark_NLO'+'\n')
f.write('generate p p > lq ta- $$ lq~ [QCD]'+'\n')
f.write('add process p p > lq~ ta+ $$ lq [QCD]'+'\n')
f.write('output LQLQ_Leptokvark_singleB'+'\n')
f.write('y'+'\n')
for mass in masses:
    m = float(mass)
    f.write('launch LQLQ_Leptokvark_singleB'+'\n')
    f.write('fixed_order = ON'+'\n')
    f.write('0'+'\n')
    f.write('set pdlabel lhapdf'+'\n')
    f.write('set lhaid 90500'+'\n')
    f.write('set nevents 1'+'\n')
    f.write('set mass 9000002 '+str(m)+'\n')
    f.write('set width 9000002 '+str(m/16/math.pi)+'\n')
    f.write('set fixed_ren_scale True'+'\n')
    f.write('set fixed_fac_scale True'+'\n')
    f.write('set mur_ref_fixed '+str(m)+'\n')
    f.write('set muf_ref_fixed '+str(m)+'\n')
    f.write('set reweight_pdf True'+'\n')
    f.write('set req_acc_fo 0.01'+'\n')
    f.write('set gul 0.1'+'\n') #doesn't matter that other terms are on, model only has u+ve, d+e, c+vmu, s+mu, b+ta 
    f.write('set gcl 0.1'+'\n')
    f.write('set gdl 0.1'+'\n')
    f.write('set gsl 0.1'+'\n')
    f.write('set gbl 0.1'+'\n')
f.close()

f=open('lqNLOxsec_single_bQuark_lambda_0p3.txt','w')
f.write('##################################'+'\n')
f.write('#                                '+'\n')
f.write('#  File to run NLO LQ production '+'\n')
f.write('#  cross section calculations in '+'\n')
f.write('#  MadGraph using the LQ toolbox '+'\n')
f.write('#  https://lqnlo.hepforge.org    '+'\n')
f.write('#                                '+'\n')
f.write('#  width = m_LQ/(16pi)           '+'\n')
f.write('#  mu_r=mu_f=m_LQ                '+'\n')
f.write('#  lamdba_lq=1.0                 '+'\n')
f.write('#                                '+'\n')
f.write('#  Ariana Gonzalez 12/2022           '+'\n')
f.write('##################################'+'\n')
f.write('import model Leptokvark/Leptokvark_NLO'+'\n')
f.write('generate p p > lq ta- $$ lq~ [QCD]'+'\n')
f.write('add process p p > lq~ ta+ $$ lq [QCD]'+'\n')
f.write('output LQLQ_Leptokvark_singleB'+'\n')
f.write('y'+'\n')
for mass in masses:
    m = float(mass)
    f.write('launch LQLQ_Leptokvark_singleB'+'\n')
    f.write('fixed_order = ON'+'\n')
    f.write('0'+'\n')
    f.write('set pdlabel lhapdf'+'\n')
    f.write('set lhaid 90500'+'\n')
    f.write('set nevents 1'+'\n')
    f.write('set mass 9000002 '+str(m)+'\n')
    f.write('set width 9000002 '+str(m/16/math.pi)+'\n')
    f.write('set fixed_ren_scale True'+'\n')
    f.write('set fixed_fac_scale True'+'\n')
    f.write('set mur_ref_fixed '+str(m)+'\n')
    f.write('set muf_ref_fixed '+str(m)+'\n')
    f.write('set reweight_pdf True'+'\n')
    f.write('set req_acc_fo 0.01'+'\n')
    f.write('set gul 0.3'+'\n') #doesn't matter that other terms are on, model only has u+ve, d+e, c+vmu, s+mu, b+ta 
    f.write('set gcl 0.3'+'\n')
    f.write('set gdl 0.3'+'\n')
    f.write('set gsl 0.3'+'\n')
    f.write('set gbl 0.3'+'\n')
f.close()

f=open('lqNLOxsec_single_bQuark_lambda_0p5.txt','w')
f.write('##################################'+'\n')
f.write('#                                '+'\n')
f.write('#  File to run NLO LQ production '+'\n')
f.write('#  cross section calculations in '+'\n')
f.write('#  MadGraph using the LQ toolbox '+'\n')
f.write('#  https://lqnlo.hepforge.org    '+'\n')
f.write('#                                '+'\n')
f.write('#  width = m_LQ/(16pi)           '+'\n')
f.write('#  mu_r=mu_f=m_LQ                '+'\n')
f.write('#  lamdba_lq=1.0                 '+'\n')
f.write('#                                '+'\n')
f.write('#  Ariana Gonzalez 12/2022           '+'\n')
f.write('##################################'+'\n')
f.write('import model Leptokvark/Leptokvark_NLO'+'\n')
f.write('generate p p > lq ta- $$ lq~ [QCD]'+'\n')
f.write('add process p p > lq~ ta+ $$ lq [QCD]'+'\n')
f.write('output LQLQ_Leptokvark_singleB'+'\n')
f.write('y'+'\n')
for mass in masses:
    m = float(mass)
    f.write('launch LQLQ_Leptokvark_singleB'+'\n')
    f.write('fixed_order = ON'+'\n')
    f.write('0'+'\n')
    f.write('set pdlabel lhapdf'+'\n')
    f.write('set lhaid 90500'+'\n')
    f.write('set nevents 1'+'\n')
    f.write('set mass 9000002 '+str(m)+'\n')
    f.write('set width 9000002 '+str(m/16/math.pi)+'\n')
    f.write('set fixed_ren_scale True'+'\n')
    f.write('set fixed_fac_scale True'+'\n')
    f.write('set mur_ref_fixed '+str(m)+'\n')
    f.write('set muf_ref_fixed '+str(m)+'\n')
    f.write('set reweight_pdf True'+'\n')
    f.write('set req_acc_fo 0.01'+'\n')
    f.write('set gul 0.5'+'\n') #doesn't matter that other terms are on, model only has u+ve, d+e, c+vmu, s+mu, b+ta 
    f.write('set gcl 0.5'+'\n')
    f.write('set gdl 0.5'+'\n')
    f.write('set gsl 0.5'+'\n')
    f.write('set gbl 0.5'+'\n')
f.close()
